##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  {{ if .Repl }}
  repl: "{{ .Repl }}"
  {{ else }}
  repl: "3"{{ end }}
  priority_io: "high"
  {{ if .Fs }}
  fs: {{ .Fs }}{{ end }}
  {{ if .AggregationLevel }}
  aggregation_level: "{{ .AggregationLevel }}"{{ end }}
allowVolumeExpansion: true
