---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-read
  labels:
    app: es-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-read
  template:
    metadata:
      labels:
        app: es-read
    spec:
      containers:
      - name: es-read
        image: portworx/elasticseach_read:v0.1
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - "./esread.sh --es_address elasticsearch:9200"
      restartPolicy: Always
