apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-sharedv4svc-nolock-wait-first-consumer-low-ha
parameters:
  repl: "2"
  sharedv4: "true"
  sharedv4_mount_options: vers=3.0,nolock
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer