/*
Copyright 2018 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/libopenstorage/stork/pkg/apis/stork/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSnapshotRestores implements SnapshotRestoreInterface
type FakeSnapshotRestores struct {
	Fake *FakeStorkV1alpha1
	ns   string
}

var snapshotrestoresResource = schema.GroupVersionResource{Group: "stork.libopenstorage.org", Version: "v1alpha1", Resource: "snapshotrestores"}

var snapshotrestoresKind = schema.GroupVersionKind{Group: "stork.libopenstorage.org", Version: "v1alpha1", Kind: "SnapshotRestore"}

// Get takes name of the snapshotRestore, and returns the corresponding snapshotRestore object, and an error if there is any.
func (c *FakeSnapshotRestores) Get(name string, options v1.GetOptions) (result *v1alpha1.SnapshotRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(snapshotrestoresResource, c.ns, name), &v1alpha1.SnapshotRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotRestore), err
}

// List takes label and field selectors, and returns the list of SnapshotRestores that match those selectors.
func (c *FakeSnapshotRestores) List(opts v1.ListOptions) (result *v1alpha1.SnapshotRestoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(snapshotrestoresResource, snapshotrestoresKind, c.ns, opts), &v1alpha1.SnapshotRestoreList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SnapshotRestoreList{ListMeta: obj.(*v1alpha1.SnapshotRestoreList).ListMeta}
	for _, item := range obj.(*v1alpha1.SnapshotRestoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested snapshotRestores.
func (c *FakeSnapshotRestores) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(snapshotrestoresResource, c.ns, opts))

}

// Create takes the representation of a snapshotRestore and creates it.  Returns the server's representation of the snapshotRestore, and an error, if there is any.
func (c *FakeSnapshotRestores) Create(snapshotRestore *v1alpha1.SnapshotRestore) (result *v1alpha1.SnapshotRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(snapshotrestoresResource, c.ns, snapshotRestore), &v1alpha1.SnapshotRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotRestore), err
}

// Update takes the representation of a snapshotRestore and updates it. Returns the server's representation of the snapshotRestore, and an error, if there is any.
func (c *FakeSnapshotRestores) Update(snapshotRestore *v1alpha1.SnapshotRestore) (result *v1alpha1.SnapshotRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(snapshotrestoresResource, c.ns, snapshotRestore), &v1alpha1.SnapshotRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotRestore), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSnapshotRestores) UpdateStatus(snapshotRestore *v1alpha1.SnapshotRestore) (*v1alpha1.SnapshotRestore, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(snapshotrestoresResource, "status", c.ns, snapshotRestore), &v1alpha1.SnapshotRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotRestore), err
}

// Delete takes name of the snapshotRestore and deletes it. Returns an error if one occurs.
func (c *FakeSnapshotRestores) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(snapshotrestoresResource, c.ns, name), &v1alpha1.SnapshotRestore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSnapshotRestores) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(snapshotrestoresResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SnapshotRestoreList{})
	return err
}

// Patch applies the patch and returns the patched snapshotRestore.
func (c *FakeSnapshotRestores) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SnapshotRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snapshotrestoresResource, c.ns, name, data, subresources...), &v1alpha1.SnapshotRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SnapshotRestore), err
}
