/*
Copyright 2018 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/libopenstorage/stork/pkg/apis/stork/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResourceTransformations implements ResourceTransformationInterface
type FakeResourceTransformations struct {
	Fake *FakeStorkV1alpha1
	ns   string
}

var resourcetransformationsResource = schema.GroupVersionResource{Group: "stork.libopenstorage.org", Version: "v1alpha1", Resource: "resourcetransformations"}

var resourcetransformationsKind = schema.GroupVersionKind{Group: "stork.libopenstorage.org", Version: "v1alpha1", Kind: "ResourceTransformation"}

// Get takes name of the resourceTransformation, and returns the corresponding resourceTransformation object, and an error if there is any.
func (c *FakeResourceTransformations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ResourceTransformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resourcetransformationsResource, c.ns, name), &v1alpha1.ResourceTransformation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceTransformation), err
}

// List takes label and field selectors, and returns the list of ResourceTransformations that match those selectors.
func (c *FakeResourceTransformations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ResourceTransformationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resourcetransformationsResource, resourcetransformationsKind, c.ns, opts), &v1alpha1.ResourceTransformationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ResourceTransformationList{ListMeta: obj.(*v1alpha1.ResourceTransformationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ResourceTransformationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resourceTransformations.
func (c *FakeResourceTransformations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resourcetransformationsResource, c.ns, opts))

}

// Create takes the representation of a resourceTransformation and creates it.  Returns the server's representation of the resourceTransformation, and an error, if there is any.
func (c *FakeResourceTransformations) Create(ctx context.Context, resourceTransformation *v1alpha1.ResourceTransformation, opts v1.CreateOptions) (result *v1alpha1.ResourceTransformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resourcetransformationsResource, c.ns, resourceTransformation), &v1alpha1.ResourceTransformation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceTransformation), err
}

// Update takes the representation of a resourceTransformation and updates it. Returns the server's representation of the resourceTransformation, and an error, if there is any.
func (c *FakeResourceTransformations) Update(ctx context.Context, resourceTransformation *v1alpha1.ResourceTransformation, opts v1.UpdateOptions) (result *v1alpha1.ResourceTransformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resourcetransformationsResource, c.ns, resourceTransformation), &v1alpha1.ResourceTransformation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceTransformation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeResourceTransformations) UpdateStatus(ctx context.Context, resourceTransformation *v1alpha1.ResourceTransformation, opts v1.UpdateOptions) (*v1alpha1.ResourceTransformation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(resourcetransformationsResource, "status", c.ns, resourceTransformation), &v1alpha1.ResourceTransformation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceTransformation), err
}

// Delete takes name of the resourceTransformation and deletes it. Returns an error if one occurs.
func (c *FakeResourceTransformations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(resourcetransformationsResource, c.ns, name, opts), &v1alpha1.ResourceTransformation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourceTransformations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resourcetransformationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ResourceTransformationList{})
	return err
}

// Patch applies the patch and returns the patched resourceTransformation.
func (c *FakeResourceTransformations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ResourceTransformation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourcetransformationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ResourceTransformation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ResourceTransformation), err
}
