##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  {{ if .Repl }}
  repl: "{{ .Repl }}"
  {{ else }}
  repl: "2"{{ end }}
  priority_io: "high"
  {{ if .IoProfile }}
  io_profile: "{{ .IoProfile }}"
  {{ else }}
  io_profile: "db_remote"{{ end }}
  {{ if .Fs }}
  fs: {{ .Fs }}{{ end }}
  {{ if .Journal }}
  journal: "true"{{ end }}
allowVolumeExpansion: true
---
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-log
provisioner: kubernetes.io/portworx-volume
parameters:
  {{ if .Repl }}
  repl: "{{ .Repl }}"
  {{ else }}
  repl: "2"{{ end }}
  priority_io: "high"
  {{ if .IoProfile }}
  io_profile: "{{ .IoProfile }}"
  {{ else }}
  io_profile: "db_remote"{{ end }}
  {{ if .Fs }}
  fs: {{ .Fs }}{{ end }}
  {{ if .Journal }}
  journal: "true"{{ end }}
allowVolumeExpansion: true

