---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdbench-fb-volumes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: vdbench-fb-volumes
  template:
    metadata:
      labels:
        app: vdbench-fb-volumes
    spec:
      schedulerName: stork
      securityContext: 
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: vdbench
          image: portworx/vdbench:torpedo
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              memory: 256Mi
              cpu: 100m
          command: ["./bench_runner.sh"]
          args: ["Basic", "5400", "$(POD_NAME)", "output/$(POD_NAME)"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: vdbench-persistent-storage
              mountPath: /tmp
            - name: vdbench-output-persistent-storage
              mountPath: /output
      volumes:
        - name: vdbench-persistent-storage
          persistentVolumeClaim:
            claimName: vdbench-pvc-fb
        - name: vdbench-output-persistent-storage
          persistentVolumeClaim:
            claimName: vdbench-pvc-output-fb

