apiVersion: stork.libopenstorage.org/v1alpha1
kind: GroupVolumeSnapshot
metadata:
  name: mysql-groupsnapshot-invalid-type
spec:
  pvcSelector:
    matchLabels:
      app: mysql
  options:
    portworx/snapshot-type: foo

