FROM golang:1.8.3
MAINTAINER harsh@portworx.com

RUN mkdir -p /go/src/github.com/portworx/torpedo

RUN wget -P /tmp/ https://get.docker.com/builds/Linux/x86_64/docker-1.12.6.tgz && \
    tar -xvf /tmp/docker-1.12.6.tgz --directory /tmp/ && \
    mv /tmp/docker/docker /usr/local/bin

WORKDIR /go/src/github.com/portworx/torpedo
