##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: tektoncd-sc
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  priority_io: "high"
allowVolumeExpansion: true
