apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-longevity-auto-journal-io-load
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: http://kubevirt-disk-registry.pwx.dev.purestorage.com/mysql-postgres-sysbench.qcow2
spec:
  storageClassName: kubevirt-longevity-io-load-auto-journal-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi