---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-longevity-auto-journal-io-load-data-volume
spec:
  storageClassName: kubevirt-longevity-io-load-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-longevity-auto-journal-io-load
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-bionic
        kubevirt-key: kubevirt-val
        app: vm-longevity-auto-journal-io-load
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
            - name: datavolume
              disk:
                bus: virtio
            - name: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 1024M
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containervolume
          persistentVolumeClaim:
            claimName: pvc-longevity-auto-journal-io-load
        - name: datavolume
          dataVolume:
            name: pvc-longevity-auto-journal-io-load-data-volume
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              chpasswd:
                list: |
                  ubuntu:ubuntu
                  root:toor
                expire: False
              runcmd:
                - while true; do
                    sysbench fileio --file-total-size=500M prepare
                    sysbench fileio --file-total-size=500M --file-test-mode=rndrw --time=30 --max-requests=0 run
                    sysbench fileio --file-total-size=500M cleanup
                    sleep 60
                  done