##### Portworx Storage Class with FADA
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-sc-fada
provisioner: pxd.portworx.com
parameters:
  backend: "pure_block"
  csi.storage.k8s.io/fstype: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
