apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win-disk-1
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win-disk-2
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win-disk-3
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win-disk-4
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win-disk-5
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win-disk-6
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win-disk-7
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win-disk-8
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win22-multi-disk
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-bionic
        app: vm-multi-disk
      annotations:
        pvc.source: "cloned"
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
            - name: datavolume1
              disk:
                bus: virtio
            - name: datavolume2
              disk:
                bus: virtio
            - name: datavolume3
              disk:
                bus: virtio
            - name: datavolume4
              disk:
                bus: virtio
            - name: datavolume5
              disk:
                bus: virtio
            - name: datavolume6
              disk:
                bus: virtio
            - name: datavolume7
              disk:
                bus: virtio
            - name: datavolume8
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            cpu: 4
            memory: 4096M
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containervolume
          persistentVolumeClaim:
            claimName: win22-boot-pvc
        - name: datavolume1
          dataVolume:
            name: win-disk-1
        - name: datavolume2
          dataVolume:
            name: win-disk-2
        - name: datavolume3
          dataVolume:
            name: win-disk-3
        - name: datavolume4
          dataVolume:
            name: win-disk-4
        - name: datavolume5
          dataVolume:
            name: win-disk-5
        - name: datavolume6
          dataVolume:
            name: win-disk-6
        - name: datavolume7
          dataVolume:
            name: win-disk-7
        - name: datavolume8
          dataVolume:
            name: win-disk-8
