apiVersion: batch/v1
kind: Job
metadata:
  name: ml-unet3d-app
spec:
  template:
    spec:
      containers:
        - name: benchmark
          image: portworx/ml-workload:mlcommons-unet3d
          command: ["/bin/bash"]
          args:
          - "-c"
          - |
            ./benchmark.sh datagen --workload unet3d --num-parallel 8 --param dataset.num_files_train=3200 &&
            while true; do
              ./benchmark.sh run --workload unet3d --num-accelerators 8 --param dataset.num_files_train=3200
              sleep 60
            done
          volumeMounts:
            - name: mlperf-data
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: mlperf-data
          persistentVolumeClaim:
            claimName: ml-unet3d-pvc