kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kubevirt-longevity-multi-pvc-sc
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  sharedv4_mount_options: vers=3.0,nolock
  io_profile: db_remote
allowVolumeExpansion: true
