kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pgbench-sc
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  priority_io: "low"
  {{ if .IoProfile }}
  io_profile: "{{ .IoProfile }}"{{ end }}
  {{ if .Fs }}
  fs: {{ .Fs }}{{ end }}
allowVolumeExpansion: true