kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sysbench-sc-secure
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
  snap_schedule: "periodic=120,1"
  {{ if .IoProfile }}
  io_profile: "{{ .IoProfile }}"
  {{ else }}
  io_profile: "db"{{ end }}
  {{ if .Fs }}
  fs: {{ .Fs }}{{ end }}
  {{ if .Journal }}
  journal: "true"{{ end }}
allowVolumeExpansion: true
