
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-db
spec:
  storageClassName: mysql-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-seq
spec:
  storageClassName: mysql-sc-seq
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-aggr
spec:
  storageClassName: mysql-sc-aggr
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi