apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  # clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-hs-nodeport
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - port: 8080
    name: metrics
  # clusterIP: None
  selector:
    app: kafka
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
spec:
  selector:
    matchLabels:
      app: kafka
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - kafka
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 300
      containers:
      - name: k8skafka
        imagePullPolicy: Always
        image: docker.pwx.dev.purestorage.com/portworx/kafka-broker
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "0.5"
        ports:
        - containerPort: 9092
          name: server
        - containerPort: 8080
          name: metrics
        command:
        - sh
        - -c
        - "exec kafka-server-start.sh /opt/kafka/config/server.properties --override broker.id=${HOSTNAME##*-} \
        --override zookeeper.connect=zk-cs:2181 \
        --override listeners=PLAINTEXT://:9092"
        env:
        # - name: KAFKA_HEAP_OPTS
        #   value : "-Xmx512M -Xms512M"
        - name: KAFKA_OPTS
          value: "-Dlogging.level=INFO -javaagent:/opt/kafka/agent/jmx_prometheus_javaagent-0.16.1.jar=8080:/opt/kafka/config/kafka_broker.yaml"
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/kafka
        # readinessProbe:
        #   exec:
        #    command:
        #     - sh
        #     - -c
        #     - "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server=localhost:9092"
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        storageClassName: zk-sc
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 64Gi
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter-metrics-sm
  namespace: kube-system
  labels:
    name: portworx-prometheus-sm
spec:
  selector:
    matchLabels:
      app: kafka
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics
    targetPort: 8080