---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vdbench-sc-sharedv4-fstrim
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  sharedv4: "true"
  nodiscard: "true"
  mount_options: "nodiscard=true"
  {{ if .Journal }}
  journal: "true"{{ end }}
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vdbench-pvc-sharedv4
spec:
  storageClassName: vdbench-sc-sharedv4-fstrim
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
