kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sysbench-sc-postgres
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "high"
  {{ if .IoProfile }}
  io_profile: "{{ .IoProfile }}"
  {{ else }}
  io_profile: "db"{{ end }}
  {{ if .Fs }}
  fs: {{ .Fs }}{{ end }}
  nodiscard: "true"
  snap_schedule: "periodic=60,5"
  mount_options: "nodiscard=true"
allowVolumeExpansion: true
