##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-fast-repl1-vps-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  placement_strategy: "fastpath-repl1-vps"
  repl: "1"
  fastpath: "true"
  priority_io: "high"
allowVolumeExpansion: true
---
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-fast-repl1-vps-log
provisioner: kubernetes.io/portworx-volume
parameters:
  placement_strategy: "fastpath-repl1-vps"
  repl: "1"
  fastpath: "true"
  priority_io: "high"
allowVolumeExpansion: true
