##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: job-pod-pvc
spec:
  storageClassName: job-pod-deployer
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
