apiVersion: v1
kind: Secret
metadata:
  name: volume-secrets
type: Opaque
data:
  vdbench-secret: dmRiZW5jaCBzaGFyZWR2NCByb2NrcyEK
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vdbench-sc-legacy-shared
provisioner: kubernetes.io/portworx-volume
parameters:
  {{ if .Repl }}
  repl: "{{ .Repl }}"
  {{ else }}
  repl: "2"{{ end }}
  {{ if .IoProfile }}
  io_profile: "{{ .IoProfile }}"{{ end }}
  {{ if .Fs }}
  fs: {{ .Fs }}{{ end }}
  shared: "true"
  nodiscard: "true"
  mount_options: "nodiscard=true"
  {{ if .Journal }}
  journal: "true"{{ end }}
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vdbench-pvc-enc-legacy-shared
  annotations:
    px/secret-name: volume-secrets
    px/secret-namespace: "_NAMESPACE_"
    px/secret-key: vdbench-secret
    px/secure: "true"
spec:
  storageClassName: vdbench-sc-legacy-shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vdbench-pvc-output-legacy-shared
spec:
  storageClassName: vdbench-sc-legacy-shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
