---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fa-raw-sc
provisioner: pxd.portworx.com
parameters:
  backend: "pure_block"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
