apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-disk-template-pvc-ea-build
  namespace: openshift-virtualization-os-images
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: http://kubevirt-disk-registry.pwx.dev.purestorage.com/more_images/fio-multi-disk.qcow2
    pvc.source: "cloned"
spec:
  storageClassName: sv4-repl2-multi-disk
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
