apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-longevity-io-load-cloudsnap
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: http://kubevirt-disk-registry.pwx.dev.purestorage.com/mysql-postgres-sysbench.qcow2
spec:
  storageClassName: kubevirt-longevity-ssie-cloudsnap
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi