---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-fa-xfs-pod
spec:
  # Specify a volume that uses the claim defined in pvc.yaml
  volumes:
  - name: nginx-vol
    persistentVolumeClaim:
        claimName: nginx-fa-xfs-pvc
  schedulerName: stork
  containers:
  - name: nginx
    image: nginx
    # Configure a mount for the volume We define above
    volumeMounts:
    - name: nginx-vol
      mountPath: /data
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-fa-ext4-pod
spec:
  # Specify a volume that uses the claim defined in pvc.yaml
  volumes:
  - name: nginx-vol
    persistentVolumeClaim:
        claimName: nginx-fa-ext4-pvc
  schedulerName: stork
  containers:
  - name: nginx
    image: nginx
    # Configure a mount for the volume We define above
    volumeMounts:
    - name: nginx-vol
      mountPath: /data
    ports:
    - containerPort: 80
