apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-disk-6
spec:
  storageClassName: test-multi-disk-low-load-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi


