apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-boot-pvc
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: http://kubevirt-disk-registry.pwx.dev.purestorage.com/more_images/fio-low-load-with-ssh.qcow2
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  storageClassName: test-multi-disk-low-load-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
