apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-shr-intree-xfs
provisioner: kubernetes.io/portworx-volume
parameters:
  fs: "xfs"
  repl: "2"
  shared: "true"
reclaimPolicy: Delete
allowVolumeExpansion: true
