apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: stork #This name is important since the Alertmanager pods won't start unless a secret named alertmanager-${ALERTMANAGER_NAME} is created. in this case, if would expect alertmanager-stork secret in the kube-system namespace
  namespace: kube-system
  labels:
    alertmanager: stork
spec:
  replicas: 3