apiVersion: v1
kind: Service
metadata:
  name: alertmanager-stork
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    alertmanager: stork