kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ml-workload-sc
provisioner: pxd.portworx.com
parameters:
  backend: "pure_file"
  pure_export_rules: "*(rw)"
mountOptions:
  - nfsvers=4.1
  - tcp
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
