apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
data:
  config.json: eyJhdXRocyI6eyJodHRwczovL2RvY2tlci5wd3guZGV2LnB1cmVzdG9yYWdlLmNvbSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJQYXNzd29yZDEiLCJhdXRoIjoiWVdSdGFXNDZVR0Z6YzNkdmNtUXgifX19
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline-run-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-role
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-role-binding
subjects:
  - kind: ServiceAccount
    name: tekton-pipeline-run-sa
roleRef:
  kind: Role
  name: tekton-role
  apiGroup: rbac.authorization.k8s.io