apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-disk-1
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2048Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-disk-2
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 120Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-disk-3
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-disk-4
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-disk-5
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-disk-6
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-disk-7
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-disk-8
  annotations:
    "cdi.kubevirt.io/storage.contentType": "kubevirt"
    "forklift.konveyor.io/disk-source": "[VCD-DEV-LINUX2-PURE-002] satdaap00886/satdaap00886_1.vmdk"
    "vmID": {{ .VmID }}
spec:
  storageClassName: sv4-wffc-localattach-multi-disk
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fio-vm-multi-disk
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-bionic
        kubevirt-key: kubevirt-val
        app: vm-multi-disk
        "vmID": {{ .VmID }}
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
            - name: datavolume1
              disk:
                bus: virtio
            - name: datavolume2
              disk:
                bus: virtio
            - name: datavolume3
              disk:
                bus: virtio
            - name: datavolume4
              disk:
                bus: virtio
            - name: datavolume5
              disk:
                bus: virtio
            - name: datavolume6
              disk:
                bus: virtio
            - name: datavolume7
              disk:
                bus: virtio
            - name: datavolume8
              disk:
                bus: virtio
            - name: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            cpu: 6
            memory: 8192M
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containervolume
          persistentVolumeClaim:
            claimName: fio-boot-pvc
        - name: datavolume1
          dataVolume:
            name: fio-disk-1
        - name: datavolume2
          dataVolume:
            name: fio-disk-2
        - name: datavolume3
          dataVolume:
            name: fio-disk-3
        - name: datavolume4
          dataVolume:
            name: fio-disk-4
        - name: datavolume5
          dataVolume:
            name: fio-disk-5
        - name: datavolume6
          dataVolume:
            name: fio-disk-6
        - name: datavolume7
          dataVolume:
            name: fio-disk-7
        - name: datavolume8
          dataVolume:
            name: fio-disk-8
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              chpasswd:
                list: |
                  ubuntu:ubuntu
                  root:toor
                expire: False
              runcmd:
                - while true; do
                    sleep 60
                  done
