apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: yes-and-fio-vm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-bionic
        kubevirt-key: kubevirt-val
        app: yes-and-fio-vm
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
            - name: datavolume1
              disk:
                bus: virtio
            - name: datavolume2
              disk:
                bus: virtio
            - name: datavolume3
              disk:
                bus: virtio
            - name: datavolume4
              disk:
                bus: virtio
            - name: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            cpu: 4
            memory: 8192M
      networks:
        - name: default
          pod: {}
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
        - name: containervolume
          persistentVolumeClaim:
            claimName: fio-boot-pvc
        - name: datavolume1
          dataVolume:
            name: fio-disk-1
        - name: datavolume2
          dataVolume:
            name: fio-disk-2
        - name: datavolume3
          dataVolume:
            name: fio-disk-3
        - name: datavolume4
          dataVolume:
            name: fio-disk-4
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              chpasswd:
                list: |
                  ubuntu:ubuntu
                  root:toor
                expire: False
              runcmd:
                - while true; do
                    sleep 60
                  done
