apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-job-config
data:
    fio.job: |
        [global]
        name=fio-rand-RW
        directory=/scratch/
        rw=randwrite
        rwmixread=90
        randrepeat=1
        blocksize=4k
        direct=1
        end_fsync=1
        do_verify=1
        verify=crc32c
        verify_pattern=0xdeadbeef
        disable_lat=0
        time_based=1
        runtime=99999999
        [file1]
        filesize=1M-10M
        nrfiles=10000
        ioengine=libaio
        iodepth=4
        rate_min=64k
        rate_iops=64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-ready-probe
data:
  ready-probe.sh: |
    #!/bin/bash
    if [ `cat /root/fio.log | grep 'error\|bad magic header' | wc -l` -ge 1 ]; then
      exit 1;
    else
      exit 0;
    fi
