---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mount-fa-sc
parameters:
  backend: "pure_block"
  {{ if .PureFaPodName }}
  pure_fa_pod_name: "{{ .PureFaPodName }}"
  {{ end }}
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
