---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mount-fa-sc
parameters:
  backend: "pure_block"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
