##### FA direct access storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-fa-da-sc
provisioner: pxd.portworx.com
parameters:
  backend: "pure_block"
  max_iops: "1000"
  max_bandwidth: "1G"
  fs: "ext4"
  {{ if .PureFaPodName }}
  pure_fa_pod_name: "{{ .PureFaPodName }}"
  {{ end }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
##### FA direct access storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-log-fa-da-sc
provisioner: pxd.portworx.com
parameters:
  backend: "pure_block"
  max_iops: "1000"
  max_bandwidth: "1G"
  fs: "ext4"
  {{ if .PureFaPodName }}
  pure_fa_pod_name: "{{ .PureFaPodName }}"
  {{ end }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

