---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: eck-operator
spec:
    channel: stable
    installPlanApproval: Automatic
    name: elasticsearch-eck-operator-certified
    source: certified-operators
    sourceNamespace: openshift-marketplace
    startingCSV: elasticsearch-eck-operator-certified.v2.12.1
