---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Agent.v1alpha1.agent.k8s.elastic.co,ApmServer.v1.apm.k8s.elastic.co,Beat.v1beta1.beat.k8s.elastic.co,ElasticMapsServer.v1alpha1.maps.k8s.elastic.co,Elasticsearch.v1.elasticsearch.k8s.elastic.co,ElasticsearchAutoscaler.v1alpha1.autoscaling.k8s.elastic.co,EnterpriseSearch.v1.enterprisesearch.k8s.elastic.co,Kibana.v1.kibana.k8s.elastic.co,Logstash.v1alpha1.logstash.k8s.elastic.co,StackConfigPolicy.v1alpha1.stackconfigpolicy.k8s.elastic.co
  name: eck-og
spec:
  targetNamespaces:
  - esop
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/elasticsearch-eck-operator-certified.test: ""
  name: elasticsearch-eck-operator-certified
spec:
  channel: stable
  installPlanApproval: Automatic
  name: elasticsearch-eck-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: elasticsearch-eck-operator-certified.v2.12.1

