apiVersion: v1
kind: PersistentVolume
metadata:
  name: fio-pv
spec:
  capacity:
    storage: 500Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: fio-pvc
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  portworxVolume:
    volumeID: fio-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fio-output-pv
spec:
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: fio-output-pvc
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  portworxVolume:
    volumeID: fio-output-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: fio-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-output-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: fio-output-pv
