apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-disk-5
spec:
  storageClassName: test-multi-disk-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi


