apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fio-vm-multi-disk
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-bionic
        kubevirt-key: kubevirt-val
        app: vm-multi-disk
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
            - name: datavolume1
              disk:
                bus: virtio
            - name: datavolume2
              disk:
                bus: virtio
            - name: datavolume3
              disk:
                bus: virtio
            - name: datavolume4
              disk:
                bus: virtio
            - name: datavolume5
              disk:
                bus: virtio
            - name: datavolume6
              disk:
                bus: virtio
            - name: datavolume7
              disk:
                bus: virtio
            - name: datavolume8
              disk:
                bus: virtio
            - name: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            cpu: 2
            memory: 4096M
      networks:
        - name: default
          pod: {}
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
        - name: containervolume
          persistentVolumeClaim:
            claimName: fio-boot-pvc
        - name: datavolume1
          dataVolume:
            name: fio-disk-1
        - name: datavolume2
          dataVolume:
            name: fio-disk-2
        - name: datavolume3
          dataVolume:
            name: fio-disk-3
        - name: datavolume4
          dataVolume:
            name: fio-disk-4
        - name: datavolume5
          dataVolume:
            name: fio-disk-5
        - name: datavolume6
          dataVolume:
            name: fio-disk-6
        - name: datavolume7
          dataVolume:
            name: fio-disk-7
        - name: datavolume8
          dataVolume:
            name: fio-disk-8
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              chpasswd:
                list: |
                  ubuntu:ubuntu
                  root:toor
                expire: False
              runcmd:
                - while true; do
                    sleep 60
                  done
