apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-sharedv4svc-nolock-immediate-low-ha
parameters:
  repl: "2"
  sharedv4: "true"
  sharedv4_mount_options: vers=3.0,nolock
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-debian-template-pvc-low-ha
  namespace: openshift-virtualization-os-images
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: http://kubevirt-disk-registry.pwx.dev.purestorage.com/more_images/debian-12-4.qcow2
    pvc.source: "cloned"
spec:
  storageClassName: sc-sharedv4svc-nolock-immediate-low-ha
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
