kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sysbench-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  nodiscard: "true"
  priority_io: "high"
  {{ if .IoProfile }}
  io_profile: "{{ .IoProfile }}"
  {{ else }}
  io_profile: "db"{{ end }}
  {{ if .Fs }}
  fs: {{ .Fs }}{{ end }}
  {{ if .Journal }}
  journal: "true"{{ end }}
allowVolumeExpansion: true
