{
 "title": "Stork Migration Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "label": "Namespace", "query": "migration_status" },
   { "name": "Name", "label": "Name", "query": "migration_status" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ClusterPair",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(clusterpair_scheduler_status{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Migrations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(migration_status{namespace=~\"$Namespace\",name=~\"$Name\"})"
    }
   ]
  },
  {
   "title": "Avg Migration Duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(migration_duration{namespace=~\"$Namespace\", name=~\"$Name\"} )"
    }
   ]
  },
  {
   "title": "ClusterPair Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(clusterpair_scheduler_status{namespace=~\"$Namespace\"} == 2 and clusterpair_storage_status{namespace=~\"$Namespace\"} == 2)",
     "legendFormat": "Ready"
    },
    {
     "expr": "count(clusterpair_storage_status{namespace=~\"$Namespace\"} == 1 or clusterpair_storage_status{namespace=~\"$Namespace\"} == 1)",
     "legendFormat": "Pending"
    },
    {
     "expr": "count(clusterpair_storage_status{namespace=~\"$Namespace\"} == 3 or clusterpair_storage_status{namespace=~\"$Namespace\"} == 3)",
     "legendFormat": "Partial Success"
    }
   ]
  },
  {
   "title": "Migration Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(migration_status{namespace=~\"$Namespace\", name=~\"$Name\"} == 5 and migration_stage{namespace=~\"$Namespace\", name=~\"$Name\"} == 5)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(migration_status{namespace=~\"$Namespace\", name=~\"$Name\"} == 2)",
     "legendFormat": "In Progress"
    },
    {
     "expr": "count(migration_status{namespace=~\"$Namespace\", name=~\"$Name\"} == 4)",
     "legendFormat": "Partial Success"
    },
    {
     "expr": "count(migration_status{namespace=~\"$Namespace\", name=~\"$Name\"} == 3)",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}