{
 "title": "Stork Application Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Namespace", "label": "Namespace", "query": "application_backup_status" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backups",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(application_backup_status{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Restores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(application_restore_status{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Clones",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(application_clone_status{namespace=~\"$Namespace\"})"
    }
   ]
  },
  { "title": "Application Controller Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total size of all backups",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(application_backup_size{namespace=~\"$Namespace\"})/ (1024 * 1024)",
     "legendFormat": "Backup Size"
    }
   ]
  },
  {
   "title": "Backup Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(application_backup_status{namespace=~\"$Namespace\"} == 5 and application_backup_stage{namespace=~\"$Namespace\"} == 5)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(application_backup_status{namespace=~\"$Namespace\"} == 2)",
     "legendFormat": "In Progress"
    },
    {
     "expr": "count(application_backup_status{namespace=~\"$Namespace\"} == 4)",
     "legendFormat": "Partial Success"
    },
    {
     "expr": "count(application_backup_status{namespace=~\"$Namespace\"} == 3)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Avg Backup Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 7 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(application_backup_size{namespace=~\"$Namespace\"}!=0)/(1024*1024)"
    }
   ]
  },
  {
   "title": "Avg Backup Duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(application_backup_duration{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Total size of all restores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(application_restore_size{namespace=~\"$Namespace\"})/ (1024 * 1024)",
     "legendFormat": "Restore Size"
    }
   ]
  },
  {
   "title": "Restore Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(application_restore_status{namespace=~\"$Namespace\"}==6 and application_restore_stage{namespace=~\"$Namespace\"}==3)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(application_restore_status{namespace=~\"$Namespace\"}==2)",
     "legendFormat": "In Progress"
    },
    {
     "expr": "count(application_restore_status{namespace=~\"$Namespace\"}==4)",
     "legendFormat": "Partial Success"
    },
    {
     "expr": "count(application_restore_status{namespace=~\"$Namespace\"}==3)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Avg Restore Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 12 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(application_restore_size{namespace=~\"$Namespace\"}!=0)/(1024*1024)"
    }
   ]
  },
  {
   "title": "Avg Restore Duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 12 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(application_restore_duration{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Clone Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(application_clone_status{namespace=~\"$Namespace\"} == 4 and application_clone_stage{namespace=~\"$Namespace\"} == 5)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(application_clone_status{namespace=~\"$Namespace\"} == 2)",
     "legendFormat": "In Progress"
    },
    {
     "expr": "count(application_clone_status{namespace=~\"$Namespace\"} == 6)",
     "legendFormat": "Partial Success"
    },
    {
     "expr": "count(application_clone_status{namespace=~\"$Namespace\"} == 3)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Avg Clone Duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 17 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(application_clone_duration{namespace=~\"$Namespace\"})"
    }
   ]
  }
 ]
}