kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ml-workload-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  priority_io: "high"
  io_profile: "db_remote"
  repl: "3"
  sharedv4: "true"
  sharedv4_svc_type: ""
allowVolumeExpansion: true