apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    startDataSupported: "true"
    username: "root"
    password: "password"
    databaseName: "mysql"
    port: "3306"
    appType: "mysql"
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: init-mysql-1
          image: busybox
          command:
            [
              "sh",
              "-c",
              "dd if=/dev/urandom of=/var/lib/mysql-aggr/mysql-test-dd-2 bs=1M count=100",
            ]
          securityContext: # Add security context for init-mysql-1
            runAsUser: 1010
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: mysql-persistent-storage-aggr
              mountPath: /var/lib/mysql-aggr
        - name: init-mysql-2
          image: busybox
          command:
            [
              "sh",
              "-c",
              "dd if=/dev/urandom of=/var/lib/mysql-seq/mysql-test-dd-2 bs=1M count=100",
            ]
          securityContext: # Add security context for init-mysql-2
            runAsUser: 1010
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: mysql-persistent-storage-seq
              mountPath: /var/lib/mysql-seq
      schedulerName: stork
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1010
      containers:
        - image: mysql:8.4
          name: mysql
          securityContext:
            runAsUser: 1010
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          livenessProbe:
            exec:
              command:
                ["sh", "-c", "mysqladmin -u root -p$MYSQL_ROOT_PASSWORD ping"]
            initialDelaySeconds: 70
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                [
                  "sh",
                  "-c",
                  'mysql -u root -p$MYSQL_ROOT_PASSWORD -e "select 1"',
                ]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - mountPath: /var/lib/mysql-aggr
              name: mysql-persistent-storage-aggr
            - mountPath: /var/lib/mysql-seq
              name: mysql-persistent-storage-seq
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-data
      - name: mysql-persistent-storage-aggr
        persistentVolumeClaim:
          claimName: mysql-data-aggr
      - name: mysql-persistent-storage-seq
        persistentVolumeClaim:
          claimName: mysql-data-seq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlslap
  labels:
    app: mysqlslap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlslap
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysqlslap
    spec:
      containers:
        - name: mysqlslap
          image: portworx/mysqlslap
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1003
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_SERVICE_PORT
              value: "3306"

