##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: job-pod-deployer
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  priority_io: "high"
allowVolumeExpansion: true