##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
spec:
  storageClassName: postgres-cephfs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
