---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kubevirt-longevity-ssie-cloudsnap
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  sharedv4_mount_options: vers=3.0,nolock
  snapshotschedule.stork.libopenstorage.org/interval-schedule: |
    schedulePolicyName: intervalpolicy
    annotations:
      portworx/snapshot-type: cloud
allowVolumeExpansion: true