---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-plane-volume
spec:
  storageClassName: kubevirt-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
