---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cdi-ubuntu
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: http://kubevirt-disk-registry.pwx.dev.purestorage.com/disk_0.img
spec:
  storageClassName: kubevirt-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
