---
apiVersion: v1
kind: Service
metadata:
  name: kubevirt-svc-nodeport
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: nodeport
      nodePort: 30000
      port: 27017
      protocol: TCP
      targetPort: 22
  selector:
    kubevirt-key: kubevirt-val
  type: NodePort
