---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data-volume
spec:
  storageClassName: kubevirt-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-ubuntu-pvc-datavolume
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu-bionic
        kubevirt-key: kubevirt-val
        app: vm-ubuntu-pvc-datavolume
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
            - name: datavolume
              disk:
                bus: virtio
            - name: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2048M
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containervolume
          persistentVolumeClaim:
            claimName: pvc-cdi-ubuntu-app
        - name: datavolume
          dataVolume:
            name: pvc-data-volume
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              chpasswd:
                list: |
                  ubuntu:ubuntu
                  root:toor
                expire: False
              scripts-user:
                -  /usr/bin/python3 /home/ubuntu/mysql_data.python &
