apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: stork
initializers:
  - name: stork.initializer.kubernetes.io
    rules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["deployments", "statefulsets"]

