---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kubevirt-longevity-io-load-sc
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  sharedv4_mount_options: vers=3.0,nolock
  io_profile: journal
allowVolumeExpansion: true