apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-job-config
data:
    fio.job: |
        [global]
        name=fio-write
        directory=/scratch/
        rw=write
        blocksize=512k
        direct=1
        end_fsync=1
        do_verify=1
        verify=crc32c
        verify_pattern=0xdeadbeef
        disable_lat=0
        [file1]
        size=80G
        ioengine=libaio
        iodepth=128