##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
   name: px-postgres-sc-sharedv4
provisioner: kubernetes.io/portworx-volume
parameters:
  {{ if .Repl }}
  repl: "{{ .Repl }}"
  {{ else }}
  repl: "3"{{ end }}
  priority_io: "high"
  sharedv4: "true"
allowVolumeExpansion: true
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-sharedv4
  labels:
    app: postgres
  annotations:
    volume.beta.kubernetes.io/storage-class: px-postgres-sc-sharedv4
    torpedo.io/autopilot-enabled: "true"
    torpedo.io/pvclabels-enabled: "true"
    torpedo.io/pvcnodes-enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      {{ if .VolumeSize }}
      storage: {{ .VolumeSize }}
      {{ else }}
      storage: 8Gi{{ end }}
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-volume-sharedv4
spec:
  storageClassName: px-postgres-sc-sharedv4
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi