apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-job-config
data:
    fio.job: |
        [global]
        name=fio-raw-rand-RW
        rw=randrw
        blocksize_range=4k-512k
        iodepth=128
        direct=1
        group_reporting
        do_verify=1
        verify=crc32c
        verify_pattern=0xdeadbeef
        disable_lat=0
        ioengine=libaio
        time_based=1
        runtime=99999999
        [job1]
        filename=/dev/pure-block-device
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grok-exporter
data:
  config.yml: |-
    global:
      config_version: 3
    input:
      type: file
      path: /logs/fio.log
      readall: false
      fail_on_missing_logfile: true
    imports:
    - type: grok_patterns
      dir: ./patterns
    grok_patterns:
    - 'FIO_IOPS [0-9]*[.][0-9]k$|[0-9]*'
    metrics:
        - type: gauge
          name: iops
          help: FIO IOPS Write Gauge Metrics
          match: '  write: %{GREEDYDATA}, iops=%{NUMBER:val1}%{GREEDYDATA:thsd}, %{GREEDYDATA}'
          value: '{{`{{if eq .thsd "k"}}{{multiply .val1 1000}}{{else}}{{.val1}}{{end}}`}}'
          labels:
              iops_suffix: '{{`{{.thsd}}`}}'
          cumulative: false
          retention: 1s
        - type: gauge
          name: bandwidth
          help: FIO Bandwidth Write Gauge Metrics
          match: '  write: io=%{GREEDYDATA}, bw=%{NUMBER:val2}%{GREEDYDATA:kbs}, %{GREEDYDATA}, %{GREEDYDATA}'
          value: '{{`{{if eq .kbs "KB/s"}}{{divide .val2 1024}}{{else}}{{.val2}}{{end}}`}}'
          labels:
              bw_unit: '{{`{{.kbs}}`}}'
          cumulative: false
          retention: 1s
        - type: gauge
          name: avg_latency
          help: FIO AVG Latency Write Gauge Metrics
          match: '     lat (%{GREEDYDATA:nsec}): min=%{GREEDYDATA}, max=%{GREEDYDATA}, avg=%{NUMBER:val3}, stdev=%{GREEDYDATA}'
          value: '{{`{{if eq .msec "(msec)"}}{{divide .val3 1000}}{{else}}{{.val3}}{{end}}`}}'
          labels:
              lat_unit: '{{`{{.msec}}`}}'
          cumulative: false
          retention: 1s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-live-probe
data:
  live-probe.sh: |
    #!/bin/bash
    if [ `ps -aef|grep fio|grep -v grep` -ne 0 ]; then 
      exit 1; 
    else 
      exit 0; 
    fi

