##### FA direct access storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-raw-block-sc
provisioner: pxd.portworx.com
parameters:
  backend: "pure_block"
allowVolumeExpansion: true
