/*
Copyright 2018 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/libopenstorage/stork/pkg/apis/stork/v1alpha1"
	scheme "github.com/libopenstorage/stork/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ApplicationRegistrationsGetter has a method to return a ApplicationRegistrationInterface.
// A group's client should implement this interface.
type ApplicationRegistrationsGetter interface {
	ApplicationRegistrations() ApplicationRegistrationInterface
}

// ApplicationRegistrationInterface has methods to work with ApplicationRegistration resources.
type ApplicationRegistrationInterface interface {
	Create(ctx context.Context, applicationRegistration *v1alpha1.ApplicationRegistration, opts v1.CreateOptions) (*v1alpha1.ApplicationRegistration, error)
	Update(ctx context.Context, applicationRegistration *v1alpha1.ApplicationRegistration, opts v1.UpdateOptions) (*v1alpha1.ApplicationRegistration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ApplicationRegistration, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ApplicationRegistrationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ApplicationRegistration, err error)
	ApplicationRegistrationExpansion
}

// applicationRegistrations implements ApplicationRegistrationInterface
type applicationRegistrations struct {
	client rest.Interface
}

// newApplicationRegistrations returns a ApplicationRegistrations
func newApplicationRegistrations(c *StorkV1alpha1Client) *applicationRegistrations {
	return &applicationRegistrations{
		client: c.RESTClient(),
	}
}

// Get takes name of the applicationRegistration, and returns the corresponding applicationRegistration object, and an error if there is any.
func (c *applicationRegistrations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ApplicationRegistration, err error) {
	result = &v1alpha1.ApplicationRegistration{}
	err = c.client.Get().
		Resource("applicationregistrations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ApplicationRegistrations that match those selectors.
func (c *applicationRegistrations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ApplicationRegistrationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ApplicationRegistrationList{}
	err = c.client.Get().
		Resource("applicationregistrations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested applicationRegistrations.
func (c *applicationRegistrations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("applicationregistrations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a applicationRegistration and creates it.  Returns the server's representation of the applicationRegistration, and an error, if there is any.
func (c *applicationRegistrations) Create(ctx context.Context, applicationRegistration *v1alpha1.ApplicationRegistration, opts v1.CreateOptions) (result *v1alpha1.ApplicationRegistration, err error) {
	result = &v1alpha1.ApplicationRegistration{}
	err = c.client.Post().
		Resource("applicationregistrations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(applicationRegistration).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a applicationRegistration and updates it. Returns the server's representation of the applicationRegistration, and an error, if there is any.
func (c *applicationRegistrations) Update(ctx context.Context, applicationRegistration *v1alpha1.ApplicationRegistration, opts v1.UpdateOptions) (result *v1alpha1.ApplicationRegistration, err error) {
	result = &v1alpha1.ApplicationRegistration{}
	err = c.client.Put().
		Resource("applicationregistrations").
		Name(applicationRegistration.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(applicationRegistration).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the applicationRegistration and deletes it. Returns an error if one occurs.
func (c *applicationRegistrations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("applicationregistrations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *applicationRegistrations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("applicationregistrations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched applicationRegistration.
func (c *applicationRegistrations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ApplicationRegistration, err error) {
	result = &v1alpha1.ApplicationRegistration{}
	err = c.client.Patch(pt).
		Resource("applicationregistrations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
