---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-fa-mount-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mount-fa-sc
---
