apiVersion: v1
kind: Service
metadata:
  name: stork-prometheus
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    prometheus: stork-prometheus