apiVersion: stork.libopenstorage.org/v1alpha1
kind: GroupVolumeSnapshot
metadata:
  name: mysql-group-cloudsnapshot
spec:
  pvcSelector:
    matchLabels:
      app: mysql
  options:
    portworx/snapshot-type: cloud
