##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-vps-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  placement_strategy: "fastpath-repl1-vps"
  repl: "2"
  priority_io: "high"
  {{ if .IoProfile }}
  io_profile: "{{ .IoProfile }}"
  {{ else }}
  io_profile: "db_remote"{{ end }}
  {{ if .Fs }}
  fs: {{ .Fs }}{{ end }}
  {{ if .Journal }}
  journal: "true"{{ end }}
  snapshotschedule.stork.libopenstorage.org/interval-schedule: |
    schedulePolicyName: intervalpolicy
    annotations:
      portworx/snapshot-type: cloud
allowVolumeExpansion: true
---
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-vps-log
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
  {{ if .IoProfile }}
  io_profile: "{{ .IoProfile }}"
  {{ else }}
  io_profile: "db_remote"{{ end }}
  {{ if .Fs }}
  fs: {{ .Fs }}{{ end }}
  {{ if .Journal }}
  journal: "true"{{ end }}
  snapshotschedule.stork.libopenstorage.org/interval-schedule: |
    schedulePolicyName: intervalpolicy
    annotations:
      portworx/snapshot-type: cloud
allowVolumeExpansion: true
